language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.4.0-preview3
      env: MODEL_PARSER=grape-swagger-entity
    - rvm: 2.4.0-preview3
      env: MODEL_PARSER=grape-swagger-representable
      env: GRAPE_VERSION=0.16.2
    - rvm: 2.4.0-preview3
      env: GRAPE_VERSION=0.17.0
    - rvm: 2.4.0-preview3
      env: GRAPE_VERSION=0.18.0
    - rvm: 2.4.0-preview3
      env: GRAPE_VERSION=HEAD
    - rvm: 2.3.2
    - rvm: 2.2.6
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: jruby-head
